=pod

=encoding utf8

=head1 command note

=over 10000

=item B< find >

C<find . -type l -print | perl -nle '-e || print'>

=item B< empty file >

    cat /dev/null >file 

    or

    : >file  # this does not fork a new process, since ":" is a builtin.

=item B< mv dir >

    (cd /source/directory && tar cf - . ) | (cd /dest/directory && tar xpvf -)
    # Move entire file tree from one directory to another
    # [courtesy Alan Cox <a.cox@swansea.ac.uk>, with a minor change]

=cut
